### ISSUE TITLE
Change Request: Pigs Turn Grass to Dirt (as opposed to loose dirt) When Eating

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/BTW-Public#171]
![Pig Suicide](https://user-images.githubusercontent.com/77890127/152658930-418b1989-2758-4b5c-b0ef-10d455cf8209.gif)
![2022-02-05_12 38 33](https://user-images.githubusercontent.com/77890127/152659010-a3027af0-3a28-4b27-8322-4263e6558667.png)

I just think it makes for weird behavior and potentially loses resources to no fault of the player.

**Comment by ammoore00** [comment]
Personally I like it as is where pigs have their own design considerations, different from other animals. FC's design for that was around pigs digging around in the dirt, whereas the other animals simply grazed on the grass.

Pigs occasionally causing themselves to fall to their death is a little quirky, but I don't see it as problematic. Dislodging attached blocks is part of the unique design consideration. The particular example you show of them dislodging sugar cane is I would imagine not intentional, as the primary case is for things like torches, where the ground they rest on is disrupted by pigs digging under them.

The sugar cane thing in particular is something I can look at, though.

**Comment by ammoore00** [comment]
So looking at the code, I think what happened here is the pig actually ate the sugar cane roots, not that they were dislodged. Regardless, I have disabled pigs' ability to eat sugar cane blocks since they can't eat the items, and it's a bigger deal now that it was before the sugar cane rework.
