### ISSUE TITLE
Change nether fortress detection to work prior to structure generation

### ISSUE THREAD

**Issue by ammoore00** [BTW-Community/BTW-Public#196]

**Comment by Hirachosan** [comment]
Maybe change their spawning to be like the strongholds, a certain number around spawn. this would make exploring the nether for a bit an actual task instead of randomly having one right under your nose, or 10k blocks out? it also makes it a lot easier to do the detection. as we could just mirror the stronghold detection from eyes of ender

**Comment by Hirachosan** [comment]
implemented in 3.0 beta
