### ISSUE TITLE
Support Mixin for addons to completely avoid editing base classes

### ISSUE THREAD

**Issue by pkstDev** [BTW-Community/BTW-Public#210]
*Some hacky ASM magic is good*

Using Mixin to do changes in the base classes in Minecraft itself should improve compatibility with other addons, as long as they don't use bad things like @Redirect or @Overwrite.

**Comment by ammoore00** [comment]
Already underway, actually :) Fabric loader support, including mixins, is totally working, it just needs some polishing to be ready for release.

**Comment by pkstDev** [comment]
Hmm, you mean the cursed legacy fabric loader fork? I think using the official loader will be better.

**Comment by Arminias** [comment]
We have put quite some effort into the loader fork to make it as compatible with BTW and its existing addons as possible. One of the main reasons we decided against using the official loader was its mostly poor support for jar mods - which BTW itself is, as well as most of its addons at this time. Additionally, we also had to edit part of fabric-loom anyway to better support core mods as well.

If we were to rewrite BTW into a fabric mod, then yes - the official loader would be the better choice. However, this is not only a tremendous amount of work, it would also mean much more than just simply rewriting all the base edits into mixins, since it would make it very difficult to read, understand and edit (with mixins) the minecraft source, when there is already a baseline of thousands of mixins being applied (just by having the rewritten BTW installed).

Besides all of that, the loader fork is made to be very compatible with all fabric mods or libraries that exist for the official fabric  loader and there are only a few edge cases where something would not work in our fork but would work in the official one.

A setup guide for BTW+Fabric is also available in the corresponding directories. Using it in MultiMC or the vanilla launcher is no problem currently. The main work that still needs to be done is, as mentioned before, some polishing as well as making the Dev-Environment easier to setup.

**Comment by ammoore00** [comment]
So I actually have a couple questions regarding rewriting BTW into a fabric mod. It's something that I'd be interested in at least considering, since it would make things a lot easier to update to later MC versions (ideally onto 1.8).

1) Is it possible to force the application order for mixins? And can another addon mixin on top of an overwrite mixin? BTW using entirely overwrite mixins would help a lot with readability if that is possible.

2) Is it possible for an addon dev environment to automatically mark said overwritten members with a comment or something directing addon authors to the location of the mixin? (or if nothing else, telling them that it is overwritten?)

**Comment by pkstDev** [comment]
> 1. Is it possible to force the application order for mixins? And can another addon mixin on top of an overwrite mixin? BTW using entirely overwrite mixins would help a lot with readability if that is possible.

According to the official docs (and some unofficial ones too), the @Overwrite annoation is not compatible with any other mixins that also do things in the same block.

**Comment by ammoore00** [comment]
Closing this as fabric is officially supported as of CE v2.0.0
