### ISSUE TITLE
Hitbox apply onHit bug

### ISSUE THREAD

**Issue by PlasmaFox256** [BTW-Community/BTW-Public#217]
Swinging a weapon/tool near a mob uses up durability and hunger without hitting it.

**Comment by ammoore00** [comment]
Client side only. It happens because the client thinks you hit and the server doesn't. Once the client is updated, it returns to the proper state. This is most noticeable if this happens on the last durability point of a weapon, causing it to reappear.

Not enough effect on gameplay to worry about fixing right now since it's purely client side.

**Comment by PlasmaFox256** [comment]
Wacky bug. Is the hunger lost clientside too?

**Comment by ammoore00** [comment]
Honestly i don't remember how hunger used when swinging works. If it only takes hunger to hit something, then yes that's client side only. If it takes hunger just to swing than you would've lost that anyways. Either way, there's no erroneous loss of hunger.

**Comment by PlasmaFox256** [comment]
Hunger is only lost when hitting an mob, swinging does not consume hunger.
