### ISSUE TITLE
Adapt visibility improvements on respiration enchant to behave properly for levels above 3

### ISSUE THREAD

**Issue by ammoore00** [BTW-Community/BTW-Public#262]
1.6 changed respiration to also help with seeing underwater - this can cause strange effects with high levels of respiration, and BTW allows for up to level 5 (which is higher than vanilla). Double check that respiration values above 3 behave properly.

**Comment by FriedYeti** [comment]
Looks broken to me. I didn't screenshot Respiration 4, but it's between 3 and 5 for effect as expected

First we have **Respiration 3:**
![2022-11-21_15 48 20](https://user-images.githubusercontent.com/13895706/203165166-e7e3a213-7d52-4639-bace-9972510f0683.png)

then **Respiration 5:**
![2022-11-21_15 48 32](https://user-images.githubusercontent.com/13895706/203165253-081c81f3-039e-4a6b-9ea2-6df29c0f0ec1.png)

and for an extra bit of fun, here's **replacing the Respiration 3 helm with the Respiration 5 helm** without removing a helmet (hovering the Resp5 helm over the equipped Resp3 helm and clicking)
![2022-11-21_15 48 42](https://user-images.githubusercontent.com/13895706/203165415-8afb2322-d2b3-48d3-bed6-9d4d16e2d9b7.png)

**Comment by Hirachosan** [comment]
Hmm, Since BTW changes up the underwater experience -> light being reduced through water. Making stuff more visible with this enchant might just be a feature that should be removed completely? gloom suddenly not being pitch black would feel really weird imo

**Comment by Hirachosan** [comment]
Or am I just imagining things? cause it kinda looks like that gloom part isn't black. If its just the non gloomy parts lighting up i think this could be nice (or on a seperate enchant)

**Comment by FriedYeti** [comment]
So yes, it definitely changes things in gloomy water, the fog seems to make it so that you can see the outline of the everything. The gloom still hides everything in black, unlike vanilla where you can see the blocks textures, but it definitely isn't pitch black anymore

BTW 1.5.2:
![2022-11-23_13 13 45](https://user-images.githubusercontent.com/13895706/203629146-d1a6ded1-102b-43a8-93bb-b2428588eb9e.png)

BTW 1.6.4:
![2022-11-23_13 09 35](https://user-images.githubusercontent.com/13895706/203629152-6f20c170-38a0-4961-a404-9c4489ad9fff.png)

Vanilla 1.6.4:
![2022-11-23_13 29 31](https://user-images.githubusercontent.com/13895706/203631464-bc3b1065-fcca-40de-a464-3f1473b57b11.png)

**Comment by ammoore00** [comment]
Honestly I think it's kind of a cool effect.

Also RE: "Since BTW changes up the underwater experience -> light being reduced through water."
BTW actually makes no edits to how light behaves underwater, with gloom being the only difference between vanilla and BTW

**Comment by LannyRipple** [comment]
Also think it is a cool effect.  Squid out of complete darkness aren't nearly as fun as is-that-maybe-a-squid-I-see?

**Comment by ammoore00** [comment]
Complete, forgot to close this issue when merging
