### ISSUE TITLE
Breaking Vegetation

### ISSUE THREAD

**Issue by PlasmaFox256** [BTW-Community/BTW-Public#287]
I thought it would be good to make vegetation a bit harder to break. Currently all flowers, grass and sugarcanes are insta broken by hand. The main issue I have with this is it always gets in the way when you mine or hit mobs. So maybe give it a 0.5s harvest time and keep at insta break for shears and axes (any effective tools). This would also indirectly buff shears and iron axes as first iron tools.

**Comment by ammoore00** [comment]
Having plants take time to harvest would not in any way affect the issue of trying to hit mobs through grass, as the issue is targeting the block at all, not whether or not it was destroyed. Hemp is not 0 hardness, yet still has that same issue. I'm willing to potentially look into some swing-through-grass style mechanic, but that would be entirely unrelated to this.

Personally I don't really see the value in adding hardness to these blocks, as I don't believe it would really affect gameplay in any meaningful way expect for being slightly more annoying in the early game. The removal of hunger cost for breaking grass is already a worthwhile enough change in that regard to encourage an axe for grass clearing, in addition to all its other benefits.

Going to leave this open for now to allow for discussion, but as it stands I don't plan on doing anything to this effect.
