### ISSUE TITLE
Witch Rework

### ISSUE THREAD

**Issue by PlasmaFox256** [BTW-Community/BTW-Public#289]
**Open for suggestions but here are some ideas to improve witches as a mob:**
-RC with shears to obtain 1 witch wart
-Change wart drops to 0-1
-Make witches "immortal" by limiting 1 max per witch hut and respawning on death (balanced cooldown)
-Remove natural witch spawns
-Reduce poison duration
-Give witches an ability to summon 1-3 bats that attack the player
-Make witches aggressive towards creepers (lore + bat farm potential)

_These changes are aimed towards more interesting gameplay and mechanics because I feel like witches have missed potential_

**Comment by ammoore00** [comment]
FC specifically removed the respawning witches at a witch hut due to the unintuitive rules surrounding bounding boxes and such, favoring natural spawns to give flexibility in farm design and placement, improving the ability to tell in game where witches are able to spawn, and also introducing interesting gameplay and design considerations for filtering out their drops from other mob drops.

The main question I have for any of this is: why? This really seems like a lot of work for very little payoff. You basically completely lose the original encouragement for players to build mob farms with item sorters in a swamp, and simply bring back the prior issues witch hut spawning had with requiring finicky mechanical knowledge beyond what is presented through gameplay.
