### ISSUE TITLE
Swing Animation

### ISSUE THREAD

**Issue by PlasmaFox256** [BTW-Community/BTW-Public#296]
Currently the player swing animation plays on each click but the actual attack speed is lower which makes fighting misleading. The animation should match hits landed.

**Comment by ammoore00** [comment]
I believe it truly does attack every time you click, just I-frames cause those attacks to not deal damage, which is an entirely separate thing and one which I don't really think is worth fixing, as the fix is in essence the 1.9 combat system.

If you can demonstrate that attack speed is limited by linking somewhere in the code, then we can talk, although I still don't think that would really be worth the development time. Otherwise I will close this.

**Comment by PlasmaFox256** [comment]
Should we leave vanilla related issues (that are known to be fixed in future releases) like lighting, desync etc?

**Comment by ammoore00** [comment]
Depends on the fix. If it is a complicated fix (like 1.7 fixing layered transparency), then I'd rather not bother with it if it is fixed between 1.6 and 1.8, unless it's a super simple backport. The reference to the 1.9 combat system was not that though, as we do not currently plan on updating to 1.9, that was just a shorthand to explain that the fix to this issue is an overhaul of combat mechanics, not a simple tweak (and that the overhaul would end up bearing resemblance to 1.9's combat system).
