### ISSUE TITLE
Early game use for XP

### ISSUE THREAD

**Issue by Blacklands** [BTW-Community/BTW-Public#320]
Right now afaik XP are almost entirely useless for a decent while of playing.
You might come across an enchantment table in a desert temple (do they always have one, or only sometimes?), but even then you might not even have leather armor yet, or iron tools, so at most you can enchant some stone tools. And then there's also no bookshelves there so you can only put level 1 enchantments on your stuff.

I personally find that kind of sad, since you can easily get to like level 20 or level 30 and then die at some point and all the XP are just gone and you never got around to do anything with them. It's also kind of annoying to constantly see the XP bar fill up more and you leveling up without you being able to do anything with that.

It also seems to go against the design of BTW where almost anything you can obtain also has some use right away, so it's not just useless to you for a long time. (There's some exceptions to that, which I'd also hope could be addressed at some point, but that's a different topic.)

I just wanted to ask if there's anything planned to maybe add an early game use for XP.
I'd have a handful of ideas myself (nothing fleshed out yet) that I could potentially turn into add-on at some point in the future to address this for myself and my co-players at least (and anyone else who feels the same). But if there's any brainstorming for this going on anywhere, I could also contribute to that.

**Comment by ammoore00** [comment]
> almost anything you can obtain also has some use right away
There's plenty of things obtainable early game which don't become useful until much later, generally potion ingredients or villager trades (mysterious gland, liver of the beast, mob heads, etc)

I get what you're saying, but I'd rather tackle this from coming up with a new that maybe xp could fit into, rather than trying to come up with something to use xp for. "Giving useless items a use" suggestions are very difficult to actually create good gameplay from, since they come at the problem from the wrong direction. So currently no plans, but if it'd fit into a future plan, then maybe. Don't want to spend any development time on it until then.
