### ISSUE TITLE
Texture packs take a long amount of time to load

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#4]
Can someone confirm this is still an issue?

If I understand the issue correctly, texture packs take a super long time to load when starting the game, but not if selected after launch. This sounds like an issue that should be easy to fix and if I recall correctly, it's related to the creation of the texture atlas.

BTW-Community/BTW-Source#10

**Comment by Justin-Erwin** [comment]
Yes, this is definitely still the case. Loading Conquest or Mesh's pack in game takes a few seconds whereas at start, it takes a few minutes. Read only-ing the option file is the current workaround to avoid forgetting to unload the pack on close.

**Comment by SimonMeskens** [comment]
Thanks for the confirmation! I'll update the labels

**Comment by SimonMeskens** [comment]
I'll leave the investigation label, since we are still looking for the root cause

**Comment by ammoore00** [comment]
It happens between these two logged lines:
```
[Texture Pack] INFO: refreshing Better Glass (pre)...
[Texture Pack] INFO: refreshing HD Font (post)...
```
and almost certainly has to do with the texture atlas like you mentioned. The time it takes to load scales with the number of textures present in the pack. My vanilla mix takes more time than default (some ctm on a few blocks but not widespread), conquest taking even more (lots of ctm but almost no items), and Mesh's pack taking the most (Mesh has an insane amount of ctm and cit in his pack)

**Comment by Hirachosan** [comment]
I seemingly pinpointed the slow texture pack processing dictated above as between refreshing Glass /HD font logs: 
`textureMap.refreshTextures()` -> line 84         `TileLoader.registerIcons(this, this.basePath, this.textureStichedMap);` during 

this led to  `TileLoader.registerIcons()` line 102 `loader.registerOneIcon(textureMap, mapName, map)` taking up  most of the time by far.

it's important to note that even when swapping texturepacks instead, this part of the loading is always taking a large time percentually, even though it takes factors less time.

during my experiments it i couldn't really pinpoint anything specific. and my feel was that everything is slower, even before this huge timesink that isn't logging anything for ever. It might be that something is slowing things down way earlier in the progress

**Comment by ammoore00** [comment]
Any insight into why it takes so much longer when loading the game vs switching packs? Switching packs does take a long time, but not nearly as long as when launching the game (by an order of magnitude).

Thanks for taking a look though, that definitely helps track it down :)

**Comment by Hirachosan** [comment]
I was comparing a light version of omega and conquest. one thing to note is that it took 1/10th of a second to register each icon. Conquest counts all the way up to 5000 while omega was done at 200 (filesize 50mb vs 5mb). Still don't know why this process takes so much more time on launch. trying to find a difference in handling but so far both seem to take the same path

**Comment by Hirachosan** [comment]
no, i take it back. it takes conquest less than a second to do all 5000. something is definitely struggling here

**Comment by Hirachosan** [comment]
` TileLoader

   private static long getTextureSize(Collection<TextureStitched> textures) {
        long size = 0;
        for (TextureStitched texture : textures) {
            size += getTextureSize(texture);
        }
        return size;
    }` seems to be the method that's taking up tens of miliseconds per texture on launch

**Comment by Hirachosan** [comment]
summary of finds: 
- `Tileloader.getTextureSize(Collection textures)` is the culprit running a quadratic loop
- Memory allocation is shown as 10 times as low during launch, this might be why it takes longer compared to switching packs.
- No differences in handling texture refresh were found for launching vs switching
- on top of running a quadratic loop, `Tileloader.getTextureSize(Collection textures)` doesn't actually return values. This seem to be because the `TextureStitched` from the map.values() don't seem to have  any values set for their size. Or because these values can't be accessed like this.
- Fixing this method me wouldn't speed up launching with a texturepack
- This method is only used in `TileLoader.registerOneIcon(textureMap, mapName, map)` Which uses it to see if an added texture is too large to save in a map, or if stitching this texture would mean that the map gets filled up.
- Currently Conquest(the biggest Texture pack around at the moment) is only using 3% of the max size the game is checking against for its biggest map (Block textures)

Proposed solutions: 
- Remove the texture size check completely, maybe add a warning?
- Maybe have a private long number `totalTextureSize` saved inTileLoader; set its initial size by a first loaded image times the number of already present images( so it's assuming all textures are of equal size as the intially presented), then add each new registered icon's size to this) to use instead for an approximate same effect.
- look into controlling memory usage.

**Comment by ammoore00** [comment]
Fixed for next release. Thanks Hiracho :)
