### ISSUE TITLE
Cows and sheep are too easy to kill by luring them into a pit

### ISSUE THREAD

**Issue by ammoore00** [BTW-Community/BTW-Public#67]
Digging a pit a couple blocks deep and then using grass to lure cows and sheep allows for incredibly easy mass killing of those animals, bypassing the gameplay elements of hunting. This is especially problematic when we want to incentivize using a bow and arrow while hunting cows.

**Comment by Hirachosan** [comment]
Easy fix maybe? Pushing animals (for a while, or chance per tick) would send them panicking

**Comment by Hirachosan** [comment]
I guess that doesn't cover all the methods that people use, but its feels thematically fitting in btw and at least makes it somewhat harder

**Comment by ammoore00** [comment]
I feel like that could get frustrating when trying to get animals into a pen, as their AI can sometimes be really stupid and require a push. Worth consideration though for sure.

**Comment by Hirachosan** [comment]
imo pushing is already really frustrating cause it hardly works, double doors (we should have double fence gates!) solves that problem! I would kinda enjoy seeing someone try pushing an animal into doing its bidding and the animal not liking it one bit :)

**Comment by ammoore00** [comment]
I can whip something up and see how it feels in playtest

**Comment by vgl266** [comment]
Hey, it's actually the only way to survive once you break out from your night shelter in a famished state at the start of the game.
You can't even hit them with your hand, but you can push them in pits and then suffocate them with dirt.
It was one of the really great "aha" moments for me, when I felt that you can fight back even from situations this dire.

**Comment by Hirachosan** [comment]
its actually a great method to gain day one food in any playthrough. and a gamey one at that. I'd say that's even more reason to nerf it :P But I do feel you in the unforgivable nature of being famished.. So many factors just stack to make stuff impossible when you're low on health( like grass, a snowball all over again) Maybe we should revise the impact of low health a bit. Or is it just me that feels the only viable way of surviving is having over half health/hunger

**Comment by vgl266** [comment]
> Or is it just me that feels the only viable way of surviving is having over half health/hunger
Well what it does is basically the same effect as if maximum health and hunger values would have been cut in half. Well, mostly hunger, cause you still can hide in quickly improvised shelter even when you are at dying state, but with hunger? Well after some point hunger makes you so useless that you could just have been dead.

**Comment by Hirachosan** [comment]
Not so sure about that MUST part.. Like, at some point you should have realized you were gonna starve if you don't gather food. just moving it to the point that you're nearly dead doesn't solve anything right? I do feel it should be a bit more lenient ( at the very least for an easy mode) but to not suffer the consequences of thinking slightly ahead feel like part of BTW to me

**Comment by vgl266** [comment]
Well the point is if you cannot do literally anything to escape death after certain hunger threshold, then you could just make hunger bar shorter without any detrimental effects to achieve the same outcome without involving any complicated mechanics since all the player can possibly do is just sit and stare at their health evaporating.
If there are no way to get food, then you can just die and start over. And to make hunger work in midgame you can do scaling of maximum hunger with exp for example (like in TFC).
So it would be better to think carefully what can be done about the issue possibly not involving creating such a situation where all the player has to do is to wait for death to come.
And if nothing good comes to the mind, and the problem still needs to be fixed, then I would go with greatly decreasing hunger penalties related to fighting mobs.
I agree that the suggestion of sending mobs to panic mode on pushing thematically fits btw, but don't forget about how devastatingly frustrating cows could become then.

**Comment by vgl266** [comment]
Now that I've said it, FC's approach to hunger detrimental effects always seemed a little weird to me. Speaking from experience here - being hungry actually makes you stronger and more aware than being full. FC kinda mixed up notions of being hungry with a notion of being malnourished. When all you have is skin and bones you are weak, sure, but when you are a strong person with meat and fat on said bones having not eaten for a day makes you even stronger than you were before. Having said that, realism <<<<< game design. But I've explained before why it could be bad from a game-design perspective too, so no need to repeat myself here.

**Comment by ammoore00** [comment]
Hunger and health penalties are something I want to look at as they may be a little too punishing right now. However, this is still a hardcore survival game. There *should* be penalties for running out of food, and I feel like doing anything too drastic to them would be straying beyond the bounds of CE's design anyways.

Also it is not uncommon for me to get down to famished on night 1 or 2 while cooking food, so there absolutely would be a difference between having you be famished and just straight killing you.

**Comment by SimonMeskens** [comment]
> Well the point is if you cannot do literally anything to escape death after certain hunger threshold, then you could just make hunger bar shorter without any detrimental effects to achieve the same outcome without involving any complicated mechanics since all the player can possibly do is just sit and stare at their health evaporating.

I feel like this is actually a very valid complaint. Gameplay should become more skill-reliant and more interesting when low hunger, not boring and single-minded or you'd be more merciful just killing the player.

> Speaking from experience here - being hungry actually makes you stronger and more aware than being full

So the US military (who do a lot of research on such topics) seems to hold the stance that in a survival situation, day 4 is when you should look for food if you haven't reached safety yet. Even earlier if you know it will take more than 3 days to reach safety. Day 4 is obviously way before the point of malnutrition for a healthy person (I once didn't eat for about 15 days and I was totally fine). From the little digging I did, it seems to be the case that people that haven't eaten in a few days start losing the ability to focus well and start making bad/risky decisions. I assume the former is because your brain is starting to ration resources and the latter is a compensating survival adaptation.

Not sure if that's in any way useful for BTW, just thought I'd mention it, since you brought up the real life consequences of not eating.

**Comment by vgl266** [comment]
> Not sure if that's in any way useful for BTW, just thought I'd mention it, since you brought up the real life consequences of not eating.

That's ok, I haven't heard about military experiments so good to know.

Thanks for bringing my attention back by the way, I think I have something which would work.

**Comment by vgl266** [comment]
> Not sure if that's in any way useful for BTW, just thought I'd mention it, since you brought up the real life consequences of not eating.

That's ok, I haven't heard about military experiments so good to know. Was going to say something about hunger, but it's too long so I'll post it elsewhere. Thanks for bringing my attention back by the way, I think I have something that could work.

So a quick recap

Q: What is the problem
A: Player being able to kill animals using pits.

Q: Under which circumstances this is a problem
A:
  1. It's not a problem when the player is hungry and thus has no other way to do it
  2. It becomes a problem when the player is not hungry
  3. And even more of a problem when they get access to lures

Q: Why is this a problem?
A: Because the player is supposed to use weapons or automated farms, so skipping it rewards the player and feels like an exploit.

So how to fix that? I've started to lay it out, but the explanation became too thorough too fast, so I may as well just post it as pseudocode. Apologies to anyone not understanding it as it is, just ask and I'll explain it. So

```
class Animal

	bool Tame

	OnNearbyAnimalAttacked()
		if not Tame
			Panic()

	Panic()
		RunAway( /* big range */ )

	OnEnemyGettingClose() // not only player, but any enemy mob
		if not Tame
			RunAway( /* small range */ )

	RunAway(range)
		// whatever code to make this happen

	OnFoodItemNearby() // if not currently running away of course
		if not Tame // eat even if not hungry
			Eat()
			Tame = True
		else if Hungry
			Eat()

	OnLuringPlayerNearby(player) // player with a lure in their hand
		if Tame()
			Follow(player)

	OnAttacked()
		Tame = False

class Cow < Animal // so cows would not attack everyone when simply making some distance between themselves and the player

	Panic()
		this.Panic()
		Attack() // everyone nearby periodically, thing cows do in BTW
```

This one still doesn't fix player's inability to gather food when hungry on first days, but that is related to the overall hunger-crippling-the-player problem, so nothing can be done right here to fix it.

**Comment by LannyRipple** [comment]
The only reason I ever smother cows is for the easy access to early leather.  So if cows that died by suffocation didn't drop leather that would leave killing them for meat which, as discussed, can sometimes be the thing that prevents a HCS.

**Comment by Hirachosan** [comment]
Doesn't solve the cheese, i was gonna say i like the approach of just not letting animals drop anything if they die by suffocating in a block.. but the i realized that still  makes pushing a pile of animals in a hole to kill them with a sword wat more profitable than the intended mechanisms.. which is the way to go anyway when you made a looting sword.

**Comment by Hirachosan** [comment]
Did you ever play test the pushing animals thing Dawn? I was thinking of a counter that ups when in contact with the player and resets after idk a day? After colliding hitboxes for 10 (?)seconds they'd start to get uncomfortable and startle. Should make passing animals no problem and i think it'd feel quite natural and would work great to combine this with leads

**Comment by LannyRipple** [comment]
You've got a looting sword and you are getting xp orbs by pushing animals
into a hole and smothering them?
I think that's how-I-want-to-play-the-game and not I-found-an-exploit.

YMMV

**Comment by LannyRipple** [comment]
This is slightly a different problem but close enough I'll mention here.  Cows in a 1x1x2 can be hit without consequence.  #development discussion at https://discord.com/channels/252863009590870017/832731036864741438/1175836604150067232

**Comment by Hirachosan** [comment]
features implemented to prevent this: no longer able to push animals around without startling them and no more item drops from suffocation damage
